### ISSUE TITLE
[TikTokClone] <Mahasweta Das>

### ISSUE THREAD

**Issue by Mahasweta-Ind** [datastaxdevs/workshop-astra-tik-tok#219]
**Name:** Mahasweta Das
**Email:** d.mahasweta2016@gmail.com
**Linkedin Profile:** <https://www.linkedin.com/in/mahasweta-das-0949b120a>

Attach the homework step I screenshots below:
-----------------------------------------
![netlifypost1](https://user-images.githubusercontent.com/87084012/126493328-f587149c-f82c-4fb6-bb53-292a46ac599c.JPG)

![netlifypostrun1](https://user-images.githubusercontent.com/87084012/126493365-84bcc8b7-a5e5-4f68-b82d-e68df2cac3cd.JPG)

![tiktokclone1](https://user-images.githubusercontent.com/87084012/126493395-df93ba60-87dc-4af7-b8de-f1ed95b15e03.JPG)

![tiktokclonenetlify](https://user-images.githubusercontent.com/87084012/126493424-147ceff7-939d-41c8-b171-d416f1862dbb.JPG)

  
Attach the homework step II screenshots below:
-----------------------------------------

<SCREENSHOTS>

**Comment by HadesArchitect** [comment]
Hey **Mahasweta Das**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/azhbIAPqRK2QGFfsIarRmQ
