### ISSUE TITLE
[HW] <Mazil Khatib>

### ISSUE THREAD

**Issue by mazilkhatib** [datastaxdevs/workshop-astra-tik-tok#30]
**Name:** <Mazil Khatib>
**Email:** <mazilkhatib786@gmail.com>
**Linkedin Profile:** <https://www.linkedin.com/in/mazil-khatib-730b62146/>

Attach the homework step I screenshots below:
-----------------------------------------

<[SCREENSHOTS](https://drive.google.com/drive/folders/1ATMlD8-SFCNNQlH1U_uVI45QCH_4Jud6?usp=sharing)>

<[DEPLOYED URL](https://adoring-montalcini-23ec01.netlify.app/)>

**Comment by RyanWelford** [comment]
Looks good Mazil! Thanks!

**Comment by SonicDMG** [comment]
Ha, I love that you shared your deployed app as well. I think it's really cool I can simply access that and Netlify will serve it from a CDN close to me. Nice job, here you go -> https://api.badgr.io/public/assertions/d6AMgxpPTQi9WmY0D7BxwA?identity__email=mazilkhatib786%40gmail.com

**Comment by SonicDMG** [comment]
BTW Mazil, looking at your images you should delete the swagger one because it contains your astra token.

**Comment by mazilkhatib** [comment]
Thanks for reviewing my work, just deleted that swagger screenshot 😅

**Comment by SonicDMG** [comment]
Of course and awesome. Have a great weekend.
