### ISSUE TITLE
[HW] SHREYAS

### ISSUE THREAD

**Issue by shreyasgadder** [datastaxdevs/workshop-astra-tik-tok#37]
**Name:** Shreyas G R
**Email:** gadderrshreyas@gmail.com 
**Linkedin Profile:** https://in.linkedin.com/in/shreyas-gadder

Attach the homework step I screenshots below:
-----------------------------------------
![Screenshot (353)](https://user-images.githubusercontent.com/68962021/119831393-de073000-bf1a-11eb-929a-3b3b6e09bd57.png)

<SCREENSHOTS>
  
Attach the homework step II screenshots below:
-----------------------------------------

<SCREENSHOTS>

**Comment by RyanWelford** [comment]
Looks like you were able to deploy successfully. Thanks, Shreyas!

**Comment by SonicDMG** [comment]
Awesome, here you go. https://api.badgr.io/public/assertions/1hBhXQk_RiKpFC2z2QRsgQ?identity__email=gadderrshreyas%40gmail.com

**Comment by shreyasgadder** [comment]
Received. Thank you very much. Looking forward to attend more such
workshops.
